### ISSUE TITLE
Super simple feature request

### ISSUE THREAD

**Issue by affiliatepayday** [wavesplatform/Waves#3575]
My feature request isn't so much a blockchain feature, as a feature of good etiquette when dealing with support issues and bugs. 

The request is, when you ask for logs, as if to imply if you get them you will reply back... actually do that. 

Its 100% rude to just drop off a conversation and never reply again after what was requested is delivered. 

I mean even if its just to say "We are clueless about this and have no idea what's going on" at least say something. 

To say nothing would be like going on to dinner with someone, and then just as the waiter is bringing the food, standing up and leaving without so much as an explanation.

**Comment by phearnot** [comment]
This is obviously related to #3538. I have to admit we did indeed lost the track of the progress with the issue because of having to deal with more pressing matters. If you feel like your issue has been neglected, consider pinging the person you contacted once again. This will also let us know the issue still persists.
