### ISSUE TITLE
Assets balances API endpoint does not return issueTransaction

### ISSUE THREAD

**Issue by a-jasinski** [wavesplatform/Waves#3637]
**Describe the bug**
Node API endpoint `[GET] /assets/balance/{address}` does not return `issueTransaction` of an asset if it was issued on a dApp through an `invokeScript` transaction.

**To Reproduce**
1. Create a dApp with a callable function which issues an Asset.
2. Invoke said function. Asset should be on the Account of the dApp.
3. Use the node API to fetch assets balances of the dApp Account with this endpoint: `[GET] /assets/balance/{address}`

**Expected behavior**
API response contains an entry of created asset with `issueTransaction` object. 

**Current behavior**
Entry of an asset is present, but its `issueTransaction` is `null`.
NOTE: Endpoint `[GET] /assets/details/{assetId}`  returns valid information about the asset.

**Screenshots**
Response example:
![waves-node-balances](https://user-images.githubusercontent.com/97729269/151150123-a0a07ff7-0739-4abc-9cc4-19b259c64ee0.png)

Details of the asset:
![waves-node-issuetx](https://user-images.githubusercontent.com/97729269/151150705-02cb02c8-c1f7-4f6f-b958-bf16d509f0e4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Version: Tested on a private node v1.3.12 running in a Docker container

**Comment by phearnot** [comment]
Actually this endpoint works as intended. Issue actions in InvokeScript transactions changed the way assets can be created in a backward-incompatible way. To make the API breakage obvious to the clients, we decided against putting InvokeScript transactions into an `issueTransaction` field (because InvokeScript transaction is not an IssueTransaction) and chose to use `null` instead.

To retrieve asset details for the whole portfolio one can use bulk request to [`/assets/details`](https://nodes.wavesnodes.com/api-docs/index.html#/assets/getMultipleAssetDetails).
