### ISSUE TITLE
Order rejected - Not enought tradable balance

### ISSUE THREAD

**Issue by me21** [wavesplatform/Waves#826]
I wanted to buy WAVES for WBTC (trade pair WAVES/WBTC).
The orders in the orderbook were:
* amount == 0.87663255 WAVES, price == 0.00064577
* amount == 733.28840417 WAVES, price == 0.000646

(I've divided amount and price values by proper power of 10 here)

I wanted to buy 3.95429043 WAVES, I had 0.00255427 BTC. It should be enough according to orderbook:
* The first order for 0.87663255 WAVES required 0.00056610 BTC,
* The second order for remaining sum of 3.07765788 WAVES required 0.00198816 BTC.

But I've got an error: Order Rejected - Not enough tradable balance: Map(8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS -> 255427, WAVES -> 19108078), needs: OpenPortfolio(Map(WAVES -> 0, 8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS -> 255447)). Why there were extra 0.00000020 BTC required?

**Comment by koloale** [comment]
Hi! It's the correct behavior because orders in the orderbook don't guarantee 100% execution (someone can get ahead of you for example). So the amount necessary to place your order is calculated at the highest price (0.000646 in your case), so to buy 3.95429043 WAVES you have to have  3.95429043 * 0.000646 = 0.00255447BTC. After your order execution, you can have  0.00000020 BTC on your account or in some cases 0 BTC.

**Comment by me21** [comment]
I see. But by time the server receives my request, couldn't it determine that no one got ahead of me and allow the request?
